### ISSUE TITLE
can we install it through NPM ?

### ISSUE THREAD

**Issue by ronycohen** [romeovs/nano-promises#2]
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/nano-promises
npm ERR! 404
npm ERR! 404 'nano-promises' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by adri** [comment]
I've published it to npm https://www.npmjs.com/package/nano-promises
Please let know when I can delete it and you publish it ;)

**Comment by ronycohen** [comment]
thx

**Comment by adri** [comment]
This doesn't work for me at all. Try pouchdb, it has a promise API that works.

**Comment by ronycohen** [comment]
ok

**Comment by romeovs** [comment]
@adri what do you mean this doesn't work? Could you provide some more information about what is wrong?

**Comment by romeovs** [comment]
It's on NPM now! version `1.2.0`
