### ISSUE TITLE
Missing db level follow support

### ISSUE THREAD

**Issue by eddiesholl** [romeovs/nano-promises#3]
Great wrapper library! If your still interested in maintaining the repo, it looks like follow is only available as a top level method, and not filtered to the DB.

Any chance this could be promoted to a dbMethod? Would you prefer a pull request?

Cheers,

Eddie

**Comment by romeovs** [comment]
This is fixed by [9d858](https://github.com/romeovs/nano-promises/commit/9d858421db4a30be17bf50c9d240889a6b673f18). Thanks for noticing! Please let me know if you have other suggestions.

**Comment by eddiesholl** [comment]
Any chance you can re-publish to npm?

**Comment by romeovs** [comment]
@eddiesholl, I don't own the npm repo so I cannot publish. I'm working on that! For now, you can install using:

```
npm install romeovs/nano-promises
```
